## Data Analytics Final Project

## Details about the Project
- Importing Libraries
- Loading and creating copy of the data
- overview and understanding the Data Frame
  - index
  - columns
  - size
  - Checking total number of Rows and Columns
  - ndim
- Indexing and Selecting Rows
   - Head
   - Tail
- Checking for Uniques Instances of the Columns
- Data Preprocessing
   - Replacing missing values
- EDA Exploratory Analysis

### Find Below the Imported Libraries

In [1]:
import numpy as np
import pandas as pd
##import matplotlib.pyplot as plt

C:\Users\ybrim\AppData\Local\Temp\ipykernel_6116\879831703.py:2: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

### Loading Data

In [2]:
device_data = pd.read_csv("Datasets/used_device_data.csv")

In [3]:
device_data

,brand_name,os,screen_size,4g,5g,main_camera_mp,selfie_camera_mp,int_memory,ram,battery,weight,release_year,days_used,used_price
0,Honor,Android,14.50,yes,no,13.0,5.0,64.0,3.0,3020.0,146.0,2020,127,74.26
1,Honor,Android,17.30,yes,yes,13.0,16.0,128.0,8.0,4300.0,213.0,2020,325,174.53
2,Honor,Android,16.69,yes,yes,13.0,8.0,128.0,8.0,4200.0,213.0,2020,162,165.85
3,Honor,Android,25.50,yes,yes,13.0,8.0,64.0,6.0,7250.0,480.0,2020,345,169.93
4,Honor,Android,15.32,yes,no,13.0,8.0,64.0,3.0,5000.0,185.0,2020,293,80.64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3449,Asus,Android,15.34,yes,no,NaN,8.0,64.0,6.0,5000.0,190.0,2019,232,89.33
3450,Asus,Android,15.24,yes,no,13.0,8.0,128.0,8.0,4000.0,200.0,2018,541,154.12
3451,Alcatel,Android,15.80,yes,no,13.0,5.0,32.0,3.0,4000.0,165.0,2020,201,78.05
3452,Alcatel,Android,15.80,yes,no,13.0,5.0,32.0,2.0,4000.0,160.0,2020,149,77.46
3453,Alcatel,Android,12.83,yes,no,13.0,5.0,16.0,2.0,4000.0,168.0,2020,176,62.31

### Creating a Copy of Data

In [5]:
## creating a copy

df = device_data.copy()

### Data Overview 
- Index
- Columns
- Size
- Checking total number of Rows and Columns
- ndim

In [6]:
device_data.index

RangeIndex(start=0, stop=3454, step=1)

In [8]:
device_data.columns

Index(['brand_name', 'os', 'screen_size', '4g', '5g', 'main_camera_mp',
       'selfie_camera_mp', 'int_memory', 'ram', 'battery', 'weight',
       'release_year', 'days_used', 'used_price'],
      dtype='object')

In [9]:
device_data.size

48356

In [13]:
print(f"=> Total Number of Rows: {device_data.shape[0]} => Total Number of Columns: {device_data.shape[1]}")

=> Total Number of Rows: 3454 => Total Number of Columns: 14

In [11]:
device_data.ndim

2

## Indexing and Selecting Rows
- head
- tail

In [14]:
device_data.head()

,brand_name,os,screen_size,4g,5g,main_camera_mp,selfie_camera_mp,int_memory,ram,battery,weight,release_year,days_used,used_price
0,Honor,Android,14.50,yes,no,13.0,5.0,64.0,3.0,3020.0,146.0,2020,127,74.26
1,Honor,Android,17.30,yes,yes,13.0,16.0,128.0,8.0,4300.0,213.0,2020,325,174.53
2,Honor,Android,16.69,yes,yes,13.0,8.0,128.0,8.0,4200.0,213.0,2020,162,165.85
3,Honor,Android,25.50,yes,yes,13.0,8.0,64.0,6.0,7250.0,480.0,2020,345,169.93
4,Honor,Android,15.32,yes,no,13.0,8.0,64.0,3.0,5000.0,185.0,2020,293,80.64

In [16]:
device_data.tail()

,brand_name,os,screen_size,4g,5g,main_camera_mp,selfie_camera_mp,int_memory,ram,battery,weight,release_year,days_used,used_price
3449,Asus,Android,15.34,yes,no,NaN,8.0,64.0,6.0,5000.0,190.0,2019,232,89.33
3450,Asus,Android,15.24,yes,no,13.0,8.0,128.0,8.0,4000.0,200.0,2018,541,154.12
3451,Alcatel,Android,15.80,yes,no,13.0,5.0,32.0,3.0,4000.0,165.0,2020,201,78.05
3452,Alcatel,Android,15.80,yes,no,13.0,5.0,32.0,2.0,4000.0,160.0,2020,149,77.46
3453,Alcatel,Android,12.83,yes,no,13.0,5.0,16.0,2.0,4000.0,168.0,2020,176,62.31

## Checking for unique Instances of columns with the uniques attrib
- main_camera_mp
- selfie_camera_mp
- int_memory
- ram
- battery
- weight

In [18]:
print(np.unique(device_data['main_camera_mp']))

[ 0.08  0.3   1.    1.2   1.3   2.    3.    3.15  4.    5.    6.5   6.7
  8.    8.1  10.   10.5  12.   12.2  12.3  12.5  12.6  13.   13.1  14.5
 16.   16.3  18.   19.   20.   20.1  20.2  20.7  21.   21.2  21.5  22.5
 22.6  23.   24.   41.   48.     nan]

In [33]:
print(np.unique(device_data['selfie_camera_mp']))

[ 0.    0.3   0.65  0.9   1.    1.1   1.2   1.25  1.3   1.6   1.8   1.9
  2.    2.1   2.2   3.    3.5   3.7   4.    5.    5.1   7.    8.    9.
 10.   10.5  12.   13.   14.   14.5  16.   16.3  18.   20.   24.   25.
 32.     nan]

In [34]:
print(np.unique(device_data['int_memory']))

[1.000e-02 6.000e-02 1.000e-01 2.000e-01 5.000e-01 4.000e+00 8.000e+00
 1.600e+01 2.400e+01 3.200e+01 6.400e+01 1.280e+02 2.560e+02 5.120e+02
 1.024e+03       nan]

In [35]:
print(np.unique(device_data['ram']))

[ 0.02  0.03  0.25  0.5   1.    1.5   2.    3.    4.    6.    8.   12.
   nan]

In [37]:
print(np.unique(device_data['battery']))

[ 500.   620.   750.   800.   820.   850.   950.  1000.  1010.  1020.
 1030.  1100.  1110.  1150.  1170.  1200.  1230.  1280.  1300.  1350.
 1400.  1420.  1430.  1450.  1470.  1500.  1510.  1540.  1560.  1600.
 1624.  1625.  1630.  1650.  1700.  1715.  1730.  1750.  1760.  1780.
 1785.  1800.  1810.  1820.  1821.  1830.  1840.  1850.  1860.  1880.
 1900.  1905.  1920.  1940.  1950.  1960.  1975.  1980.  2000.  2020.
 2030.  2040.  2050.  2060.  2070.  2100.  2110.  2125.  2130.  2140.
 2150.  2180.  2200.  2210.  2230.  2250.  2256.  2260.  2280.  2300.
 2320.  2330.  2350.  2370.  2390.  2400.  2410.  2420.  2430.  2440.
 2450.  2460.  2470.  2480.  2500.  2515.  2520.  2525.  2530.  2540.
 2550.  2560.  2580.  2600.  2610.  2620.  2630.  2640.  2650.  2658.
 2660.  2670.  2680.  2691.  2700.  2705.  2710.  2716.  2730.  2750.
 2760.  2770.  2800.  2820.  2840.  2850.  2860.  2865.  2870.  2880.
 2900.  2910.  2915.  2920.  2930.  2942.  2950.  2955.  2960.  2965.
 2970.  2980.  2990.  3000.  3010.  3020.  3030.  3046.  3050.  3060.
 3065.  3070.  3075.  3080.  3090.  3095.  3100.  3110.  3120.  3130.
 3140.  3150.  3160.  3174.  3180.  3200.  3210.  3220.  3225.  3230.
 3235.  3240.  3250.  3260.  3300.  3315.  3320.  3330.  3340.  3350.
 3360.  3400.  3410.  3425.  3430.  3450.  3480.  3500.  3510.  3520.
 3540.  3550.  3570.  3580.  3590.  3600.  3610.  3620.  3630.  3650.
 3700.  3730.  3750.  3760.  3765.  3800.  3820.  3830.  3850.  3900.
 3910.  3930.  3937.  3940.  3950.  3969.  4000.  4010.  4015.  4020.
 4025.  4030.  4035.  4045.  4050.  4060.  4065.  4070.  4080.  4085.
 4100.  4120.  4130.  4150.  4160.  4180.  4200.  4230.  4235.  4250.
 4260.  4270.  4290.  4300.  4315.  4350.  4360.  4380.  4400.  4420.
 4450.  4500.  4520.  4550.  4600.  4680.  4700.  4720.  4780.  4800.
 4850.  4890.  4900.  4960.  5000.  5020.  5070.  5100.  5124.  5180.
 5200.  5260.  5300.  5400.  5493.  5500.  5680.  5770.5 5830.  5870.
 5900.  5910.  6000.  6020.  6100.  6150.  6180.  6190.  6200.  6340.
 6400.  6470.  6600.  6660.  6700.  6800.  7000.  7040.  7250.  7280.
 7300.  7306.  7340.  7400.  7500.  7600.  7800.  7812.  7900.  8000.
 8134.  8200.  8220.  8380.  8400.  8600.  8620.  8827.  9000.  9240.
 9300.  9500.  9600.  9720.     nan]

In [38]:
print(np.unique(device_data['weight']))

[ 69.    75.    77.9   78.2   78.4   78.6   79.    80.    81.    82.6
  83.6   85.    86.5   87.5   88.1   88.2   89.    89.2   89.3   89.6
  90.    90.5   91.    91.3   91.8   92.    93.    95.    96.    97.
  97.3   97.7   98.    98.2   98.6   98.9   99.5   99.8  100.   100.5
 100.6  101.   101.1  101.3  102.   103.   103.3  103.7  104.5  104.6
 105.   106.   107.   107.6  108.   109.   110.   110.2  110.3  110.6
 111.4  112.   113.   113.4  113.6  114.   114.5  115.   115.3  115.35
 115.4  115.5  116.   117.   117.4  117.9  118.   118.2  118.5  118.7
 118.8  118.9  119.   119.1  119.5  119.8  120.   120.6  121.   121.1
 121.9  122.   122.5  122.7  123.   123.3  123.8  123.9  124.   124.4
 124.9  125.   125.3  125.9  126.   126.5  126.6  127.   127.6  127.9
 128.   128.5  128.7  129.   129.4  129.6  130.   130.1  130.3  130.4
 130.5  131.   131.5  131.9  132.   132.5  133.   133.2  133.5  134.
 134.1  134.2  135.   135.5  135.55 135.6  135.8  136.   136.1  136.3
 136.5  136.6  136.9  137.   137.4  137.5  137.7  138.   138.3  138.5
 138.9  139.   139.1  139.2  139.3  140.   140.1  140.45 140.5  140.6
 140.7  140.75 141.   141.2  141.5  141.8  141.9  142.   142.5  142.6
 142.9  142.95 143.   143.1  143.5  143.6  143.8  143.9  144.   144.6
 144.9  145.   145.2  146.   146.4  146.5  146.7  146.8  147.   147.2
 147.5  147.6  147.7  148.   148.5  148.8  148.85 149.   149.1  149.3
 149.5  149.7  149.8  150.   150.5  151.   151.3  152.   152.9  153.
 153.2  153.4  153.5  153.7  153.8  154.   154.5  154.85 155.   155.1
 155.3  155.6  156.   156.2  156.5  157.   157.5  157.8  158.   158.4
 158.6  158.8  159.   159.5  159.9  159.95 160.   161.   162.   162.5
 162.8  163.   163.3  163.5  163.9  164.   164.4  165.   165.4  165.9
 166.   166.5  167.   167.4  167.5  167.6  167.8  167.9  168.   168.1
 168.2  168.5  169.   169.5  169.8  170.   170.1  170.6  171.   171.1
 171.5  171.7  171.8  172.   172.3  172.5  172.9  173.   173.4  173.8
 174.   174.9  175.   176.   176.5  176.6  176.9  177.   177.6  178.
 179.   180.   180.3  181.   181.4  181.5  182.   183.   183.2  183.5
 183.6  184.   184.7  184.8  185.   186.   186.7  187.   187.1  188.
 189.   189.4  189.5  189.9  190.   190.2  190.25 190.5  191.   191.5
 191.6  192.   193.   194.   194.8  195.   196.   196.3  196.5  196.6
 196.8  197.   198.   198.1  198.5  199.   200.   201.   201.8  202.
 203.   204.   204.1  204.4  205.   206.   206.5  207.   207.7  208.
 209.   209.8  210.   211.   212.   213.   214.   214.5  215.   217.
 217.3  218.   218.5  219.   219.5  220.   221.   222.   223.   225.
 226.   228.   229.   230.   232.   233.   234.   236.   238.   239.
 240.   241.   242.   243.   244.9  245.   250.   253.   254.   256.
 259.   260.   263.   265.   269.   270.   272.   276.   278.   279.
 280.   282.   283.   285.   289.   290.   292.   293.   294.   294.8
 295.   295.1  298.   299.   300.   300.5  302.   303.   305.   306.
 309.   310.   310.5  313.   314.   315.   316.   318.   319.8  320.
 322.   323.   325.   326.   327.   328.   329.   330.   331.   335.
 337.   338.   339.   339.9  340.   340.2  342.   342.5  344.   345.
 347.   350.   353.8  354.4  355.   356.   357.   358.   360.   364.
 369.   370.   372.   374.   380.   384.   389.   390.   393.   400.
 401.   402.   404.   406.   410.   415.   419.   420.   425.   426.
 429.   430.   433.   437.   439.   450.   453.6  456.   460.   465.
 467.   467.2  468.   469.   470.   471.   472.4  475.   477.   480.
 483.   485.   487.   489.   490.   495.   498.   500.   505.2  508.
 509.   510.   517.   520.   522.   523.   525.   535.8  540.   544.3
 550.   560.   580.   585.   595.   597.   598.7  605.   612.   615.
 619.   620.   621.   626.   630.5  631.   637.   641.   645.4  653.
 655.   660.   666.8  671.3  675.9  677.   680.   713.   730.2  732.
 740.   750.   753.   850.   855.      nan]

## Data Preprocessing 
- Checking Data types Using the dtype function
- Group data types into categorical and non-categorical
- Filling in Missing Values Using MEAN Function

#### Check for Data types

In [41]:
device_data.dtypes

brand_name           object
os                   object
screen_size         float64
4g                   object
5g                   object
main_camera_mp      float64
selfie_camera_mp    float64
int_memory          float64
ram                 float64
battery             float64
weight              float64
release_year          int64
days_used             int64
used_price          float64
dtype: object

#### Grouping Data into Types

In [42]:
device_data.head()

,brand_name,os,screen_size,4g,5g,main_camera_mp,selfie_camera_mp,int_memory,ram,battery,weight,release_year,days_used,used_price
0,Honor,Android,14.50,yes,no,13.0,5.0,64.0,3.0,3020.0,146.0,2020,127,74.26
1,Honor,Android,17.30,yes,yes,13.0,16.0,128.0,8.0,4300.0,213.0,2020,325,174.53
2,Honor,Android,16.69,yes,yes,13.0,8.0,128.0,8.0,4200.0,213.0,2020,162,165.85
3,Honor,Android,25.50,yes,yes,13.0,8.0,64.0,6.0,7250.0,480.0,2020,345,169.93
4,Honor,Android,15.32,yes,no,13.0,8.0,64.0,3.0,5000.0,185.0,2020,293,80.64

In [43]:
numerical = ['screen_size', 'main_camera_mp', 'selfie_camera_mp', 'int_memory', 'ram', 'battery', 'weight', 'release_year', 'days_used', 'used_price']

categorical = ['brand_name', 'os', '4g', '5g']